### ISSUE TITLE
[Bug] Banner Notifications Disrupt Stream on iPad - iPhone 6 not affected

### ISSUE THREAD

**Issue by khb008** [limelight-stream/limelight-ios#13]
I reported earlier that the banner notifications on the iPad cause the stream's video to turn black.  The audio remains intact and is reactive to the controller.  There is no sign of this on the streaming computer, and the stream does not return to normal once the banner notification has disappeared.

**Comment by dwaxemberg** [comment]
this was fixed a while back and should no longer affect the new releases. closing it
