### ISSUE TITLE
[Feature] Touch controls for missing buttons on MFi Controllers

### ISSUE THREAD

**Issue by Kyahx** [limelight-stream/limelight-ios#23]
On iOS I imagine most users will be using a MFi certified controller.  Due to the MFi controller spec, none of those controllers will include L3, R3, Back, or Guide button.  I think a possible solution for this would be to place soft-controls on screen to account for the missing buttons, or use swipes / gestures as appropriet.

For example I am use a Moga Rebel with my iPhone 6+.  I would image a tap in the lower left square of the screen for L3, a tap in the lower right square for R3, a double-tap anywhere for the Guide button to bring up the steam overlay, and a maybe a swipe from the left edge of the screen to trigger the Back button.

This concept could be further expanded to allow playing controller based games purely on the touchscreen (which could make sense on a large device like the iPad) without even needing a hardware controller, or for allowing basic MFi controllers (like the Logitech Powershell or Razer Junglecat) to use the full range of buttons.

Additionally if Limelight is ever published in the App Store then Apple's guidelines require physical controller support to be optional (so touch controls would be a requirement anyways).

**Comment by dwaxemberg** [comment]
this was added by 25d815dcd787bd56db49bf60eda7d8e156c90342
closing issue
