### ISSUE TITLE
Solution for L3 and R3 buttons?

### ISSUE THREAD

**Issue by sevansup** [limelight-stream/limelight-ios#24]
UPDATE: "Controllers for all" appears to be working fine with the latest build, however I'd like to ask if there are plans to somehow include support for L3 and R3 thumbstick buttons that are standard in console controllers. I know that MFI controllers don't use those 2 buttons, but I think it'll be rather difficult to play a lot of PC games without them. Any ideas?

Thanks for the hard work!

**Comment by mattmaddux** [comment]
I didn't think this would really be much of an issue until I switched from playing with the controller attached directly to the host to using it paired with the phone (DS4, ControllersForAll).  The inability to use the L3, R3 and Back buttons cripples some games.  It was honestly a surprise to me how much they were being used.  I could see adding ( maybe invisible?) virtual buttons on the screen, perhaps.  Tap the bottom left corner for L3, bottom right for R3 and bottom center for Back.  Something like that could work.

**Comment by dwaxemberg** [comment]
L3 and R3 have been implemented as part of the on-screen controls. closing this issue.
