### ISSUE TITLE
Controllers For All

### ISSUE THREAD

**Issue by rcsrex** [limelight-stream/limelight-ios#30]
Having a jailbroken device, I was wondering if using a PS4 controller with Controllers For All and then running Limelight would work. And if it does, do I need to set it up somewhere?

**Comment by dwaxemberg** [comment]
Closing this issue since Controllers For All is supported.

**Comment by joopjuh** [comment]
Currently the PS4 controller isn't working on iOs 8.3 with updated controllers for all.
Only button that works is the home button.
