### ISSUE TITLE
Unable to exit/close stream on PC from within the app.

### ISSUE THREAD

**Issue by Lando9999** [limelight-stream/limelight-ios#43]
On the android version of Limelight, in the Games List I can touch the last game I played and it will give me the option to either Resume Session or Exit Session.  On the iOS version when I touch the last game played it automaticlly launches the current stream again, I don't get the option to close session. I can't find a way to close the current stream/session down on my PC from within the iOS app.

I'm new to iOS, I've only had my iPad for 6 days, possibly I'm just overlooking something simple or is this feature not implented yet? 

Thanks in advanced

iPad Mini (2nd Gen)
JB TaiG
IOS 8.1.2

**Comment by dwaxemberg** [comment]
Added this feature in 0e2765ad86faaea18b03ee6e010c480d2b3490f5
Will be included in the next build

**Comment by Lando9999** [comment]
Awesome! Thank you.
