### ISSUE TITLE
4:3 Support?

### ISSUE THREAD

**Issue by gamblor420** [limelight-stream/limelight-ios#47]
Someone posted a pic of themselves playing Portal 2 I believe with an aspect ratio of 4:3 and 2000 x 1500 resolution. Whenever I try to duplicate those settings I still get black bars on the top and bottom.  Is there something I'm doing wrong or is this ratio not supported properly at this time?

**Comment by gamblor420** [comment]
Sorry I forgot to add that this was for an iPad air 2.

**Comment by betrisey** [comment]
In the Limelight's settings, you need to set the resolution to "Native".
If you haven't this option, this will be available in the next build.

**Comment by betrisey** [comment]
I have built the project today, you can download and install : https://www.dropbox.com/s/jogzckiphwamc6r/Limelight-02.01.2014.ipa?dl=0
It features 4:3 support, on screen control and the new black UI.

**Comment by gamblor420** [comment]
Thank you very much. I am loving the icon and black theme. Also blown away you inplemented touch controls!!!  Keep up the excellent work!

**Comment by betrisey** [comment]
@gamblor420 I have only implemented the native resolution support and created the icon. But thank you :)
Can you please close the issue.
