### ISSUE TITLE
[Bug] Pulling up control center stops stream

### ISSUE THREAD

**Issue by Aghassi** [limelight-stream/limelight-ios#5]
If you are in the middle of a stream and you pull up control center, the stream will stop on your device, but not on your computer. You can always re-connect, and re-establish a connection, but if a person is, for example, streaming TF2 and accidentally pulls up control center mid game, that is not good.

**Comment by dwaxemberg** [comment]
Closing this and created https://github.com/limelight-stream/limelight-ios/issues/84 to address the background option.
