### ISSUE TITLE
Unable to connect to host

### ISSUE THREAD

**Issue by TheWispy** [limelight-stream/limelight-ios#56]
This is my first download of limelight. I've entered the IP of my PC (as the IPv4 listed in my command prompt) into limelight, but it says "Host Not Found - Unable to connect to host: <myip>".

**Comment by silentverdict** [comment]
Are you doing this remotely? If you're on the same network the PC should show up with you entering it in, if you're doing this remotely, you'll need to make sure you're forwarding the right ports on your router, or you won't be able to find it or connect. 

Ports to forward manually:
TCP 35043, 47984, 47989, 47995, 47996, 48010
UDP 47998, 47999, 48000

**Comment by TheWispy** [comment]
I wasn't doing this remotely, however my problem was that my GFE wasn't actually on. So I think that's this "issue" resolved. Thank you very much anyway :)
