### ISSUE TITLE
[Bug] Same PC shows up in host list 8 times

### ISSUE THREAD

**Issue by leshric** [limelight-stream/limelight-ios#57]
When I first used limelight on my iPhone 6+, my two PC's only showed up once each. Later, all of a sudden, they both show up 8 times each. I can make it work by clicking on any of them. They still only show up once on my iPad mini w/ retina connected to the same network.

**Comment by REJack** [comment]
i have the same issue on my iPhone 5S 'n iPad mini too

**Comment by Athanaetos** [comment]
It seems to be a problem with the latest update, was going to post this here.

**Comment by REJack** [comment]
i have the same issue in the 0.2.2 and 0.3.0 build

**Comment by TheWispy** [comment]
Using an iPod touch 5, I found that removing the hosts and rejoining sorted it. Maybe the ability to select multiple PCs (or manipulate their position on the UI) would be helpful.

**Comment by Athanaetos** [comment]
Tried removing hosts, they just seem to reappear and a lot more as well. It seems like they are multiplying, I literally have an infinite list of the same computer.

**Comment by swotai** [comment]
I think this is the same issue as mine.  My PC show up 3 times in Limelight's list.  Also they show up as "Pair State Unknown", I don't know if it is related.

**Comment by dwaxemberg** [comment]
Is this still happening in 0.4? 
Note, you may need to manually remove the duplicates the first time, but they should no longer reappear.

**Comment by dwaxemberg** [comment]
This is fixed in fab8d604d2be76a35c7dd907f87b6e9860518b4c
If you notice you have multiple hosts, remove them and they should no longer reappear.
