### ISSUE TITLE
[Bug] Quality setting in new update doesn't do anything

### ISSUE THREAD

**Issue by Athanaetos** [limelight-stream/limelight-ios#58]
In version 0.3.2 (the latest version) I am experiencing problems with the Mbps slider. I see no difference in lower settings, 1-10 Mbps, compared to really high settings, 40-50 Mbps. Before when the slider was Kbps, the difference was noticeable. I am getting stutters every few seconds and low quality on 50 Mbps. Before, I used to play on 50, 000 Kbps with out any issues or low quality. I am not sure what this is as no hardware has changed. Just wanted to put this here.

**Comment by gamblor420** [comment]
I have encountered this exact problem. The streaming quality looks very pixelated and choppy when there is a lot of movement on the screen. I'm thinking it has to do with the new GeForce experience update. I couldnt take it anymore so I downgraded my GeForce and went back to a previous build. I hope this issue gets resolved soon.

**Comment by DigiDak** [comment]
I'm also having this issue on iPhone 5S, and GeForce Experience 2.2.2.0

**Comment by DigiDak** [comment]
This is happening to me too. 
Lots of freezing and artifacting, no mater what setting.

**Comment by silentverdict** [comment]
This is also happening to me, I rolled back to the last version to fix it for the time being until they sort this out.

**Comment by dwaxemberg** [comment]
I believe this issue is fixed in 0.4 as part of c205b99080f2612e591a7d14a840e259fe903384, can someone confirm?

**Comment by gamblor420** [comment]
I am still getting a lot of pixelation with the new build.
