### ISSUE TITLE
[Question] New GFE, multiple controller support?

### ISSUE THREAD

**Issue by Athanaetos** [limelight-stream/limelight-ios#59]
I know I've been posting a lot recently, but was wondering if the new multiple controller support will work with Limelight. There was a update for the Nvidia  Shield hub app which allows multiple controllers to work and play streamed games. I was wondering if this is a change to the new GFE and could also be a possibility with Limelight.

**Comment by ikogan** [comment]
I too am curious about this situation. I've been trying to play games like Castle Crashers or emulators and things and have been forced to run wires to my living room rather than streaming. Are there any plans to support this?

**Comment by cgutman** [comment]
Yes, Android supports it as of today. Adding support to common-c and iOS should be trivial.

**Comment by Athanaetos** [comment]
That'll be really cool to see, I am not even sure if it is possible to connect more than one controller to an iOS device.

**Comment by gu3st** [comment]
It is.

**Comment by Athanaetos** [comment]
How about through Controllers For All? The Jailbreak tweak. I use it for PS4 controller, and wonder if I can connect more than one?

**Comment by ikogan** [comment]
In case anyone's wondering (please correct me if I'm wrong) but this feature is not yet available in the release builds on the Play store. It does work perfectly and wonderfully from source on the Nexus Player.

**Comment by dwaxemberg** [comment]
These commits added support for multiple controllers:
93119f25a680cba54f1ec327a2981510f917dbd7
c7c28a18c5297458b3187b3bc5807dadf7c0207a
e31df3f44ec88bba0aea34afdb8282c73561164f

Please note, I have not tested if multiple controllers work with Controllers For All. However, using 2 MFI controllers does work.
Closing issue.
