### ISSUE TITLE
[Bug] L3 and R3 not showing up on touch controls 

### ISSUE THREAD

**Issue by gamblor420** [limelight-stream/limelight-ios#64]
Can't seem to find L3 or R3 on the latest beta build.

**Comment by gamblor420** [comment]
Anyone else noticing this issue?

**Comment by dwaxemberg** [comment]
Can you be a little more specific? Which touch controls settings are you using? Do you have a physical controller attached?

**Comment by gamblor420** [comment]
I have tried both controller settings and neither have l3 or r3. The simple controller settings has l2 r2 instead of l3 r3. I have tried it with and without my physical controller but it still fails to display the l3 r3 buttons.

**Comment by dwaxemberg** [comment]
@gamblor420 On the full controls page there are no L3 and R3 buttons, the way it works is you tap the analog stick then touch and hold to activate L3/R3. Note you must do this within 100 ms to activate L3/R3.

**Comment by gamblor420** [comment]
Thank you for responding. I'll just use the full controls for the meantime. Can't tell you how awesome it is to stream games to my iPad!!!

**Comment by abattrick** [comment]
With newest experience released I can no longer connect the dial just spins as if loading pc. It says the pc is online.

**Comment by dwaxemberg** [comment]
Fixed in 8d3e81ed25bc7d2c67a3bc4c8f6b4f249e8db4f0
