### ISSUE TITLE
[Question] New iTunes Connect?

### ISSUE THREAD

**Issue by Athanaetos** [limelight-stream/limelight-ios#68]
The Test Flight no longer works, and is replaced with iTunes Connect. How would I go about joining the new one if it exists? Thank you!

**Comment by dwaxemberg** [comment]
TestFlight was acquired by apple and is now an app on the App Store. I transferred all beta testers from TestFlight to iTunes connect and you should be able to install Limelight using the new TestFlight app.

**Comment by Athanaetos** [comment]
I see, that's the problem. The e-mail given to you, is not the same as my Apple ID. If I give you my ID will you add it in?

My ID: k.ali.b98@icloud.com
Friends ID: khb008@icloud.com
(My friend also has the exact problem, I hope you can add him too)

Thank you very much!

**Comment by abattrick** [comment]
Do we still use testflight? Cuz I can't log in to iTunes connect it says I'm not registered

**Comment by dwaxemberg** [comment]
@abattrick  You don't need to login to iTunes connect. You need to go to the App Store and download the new TestFlight app.
@Athanaetos I have added both of your emails and you should receive an invite shortly. Please note that it is not required that you use an iCloud email address. Any email address should work as long as you have access to it on your iDevice.

**Comment by sevansup** [comment]
Looks like I no longer have access with the new Testflight. Would you mind inviting me again?

sevansup@gmail.com

I'd love to continue testing. Thanks a bunch!

**Comment by dwaxemberg** [comment]
@sevansup You have been added to the new system. Make sure to download the new TestFlight App from the App Store.
