### ISSUE TITLE
how do i install?

### ISSUE THREAD

**Issue by radderboy9** [limelight-stream/limelight-ios#74]
i was wandering how i might be able to install the limelight files onto my ios device?

**Comment by nigerson** [comment]
You either need to be granted beta access and download from appstore, or jailbreak your device and download the "limelight-ios-master" zip folder. Then go to Builds and install the newest version. Just a fair warning the games aren't really playable at this point, I mean they run and all, but I get around .5 sec of video lag and choppy sound vs. minimal/no lag on android. I'm also not sure of any ios controller that supports L3/R3 buttons so in games like COD you can't knife and run.

**Comment by dwaxemberg** [comment]
@radderboy9 you have been added to the beta list. Please wait for the next build to be released.
