### ISSUE TITLE
Beta test

### ISSUE THREAD

**Issue by Exorch** [limelight-stream/limelight-ios#79]
Hi,I'd like to beta test on my iPhone.
My email is exorch@gmail.com

**Comment by FlyingTitan** [comment]
Figured that I would post here instead of opening another issue:
I would also like to apply for beta testing, I have alpha/beta tested many other software packages before and can provide detailed feedback / bug reports.
If you are still accepting, my email address is peter.hurt@sky.com

**Comment by abattrick** [comment]
Is this not compatible with the newest GeForce experience? I can no longer connect to pc when I load a game. It shows pc and my games but when connecting it says can not connect

**Comment by dwaxemberg** [comment]
@Exorch added, you will receive an email when the next beta is released
