### ISSUE TITLE
Beta Testing

### ISSUE THREAD

**Issue by Nuke195** [limelight-stream/limelight-ios#80]
Hello, it would be a pleasure to join the beta and test it on my ipad 4 and iphone 5c.

My email: athakkar777@gmail.com

**Comment by zearthur99** [comment]
I also would like to test the beta version. iPhone 5S.

e-mail: ze_arthur101@hotmail.com

**Comment by dwaxemberg** [comment]
Added, you will receive an email when the next build is released
