### ISSUE TITLE
DS4 L3/R3 problem

### ISSUE THREAD

**Issue by nigerson** [limelight-stream/limelight-ios#81]
The controller seems to work fine apart from the L3 and R3 buttons not responding.

**Comment by Athanaetos** [comment]
They do not function for iOS in general due to limitations of the controller support I believe.

**Comment by dwaxemberg** [comment]
@nigerson The MFI protocol that Apple uses for gamepads does not support L3/R3. There is nothing we can do on our end other than supply the on-screen control version.
