### ISSUE TITLE
"Controllers For All" - Keyboard Mode is a no-go?

### ISSUE THREAD

**Issue by MukiEX** [limelight-stream/limelight-ios#83]
I've gotten "Controllers For All" to work with a Dual Shock, but the Keyboard mode, which lets me use an iCade or iPega controller without disabling my system's non-BTStack Bluetooth, doesn't seem to work. Is there some type of "hook" for C4A missing?

Other iOS apps seem to function with the keyboard mode (tested Sonic CD), so it might be related to the other issue with general keyboard functionality.

**Comment by dwaxemberg** [comment]
Limelight currently does not support keyboard input (through C4A or a hardware keyboard). There is an open issue for this already: https://github.com/limelight-stream/limelight-ios/issues/37
